### ISSUE TITLE
skeleton-typescript-webpack does not work with aurelia-testing

### ISSUE THREAD

**Issue by dstroyrofworlds** [aurelia/testing#21]
See [570](https://github.com/aurelia/skeleton-navigation/issues/570)

I installed aurelia-testing:

```
npm install aurelia-testing --save-dev
```

I added a custom element:
test.html

``` html
<template>Hi</template>
```

I added a test:

``` javascript
import './setup';
import {StageComponent, ComponentTester} from 'aurelia-testing';
import {bootstrap} from 'aurelia-bootstrapper-webpack';

describe('The test widget', () => {

    let component;

    beforeEach(() => {

        component = StageComponent
            .withResources(['./src/test.html','test.html','src/test'])
            .inView('<test></test>');
    });


    afterEach(() => {
        component.dispose();
    });


    it(' should work', (done: DoneFn) => {
        component.create(bootstrap).then(() => {
            done();
        });
    });

});
```

The **withSources** - I tried './src/test.html', 'test.html' - nothing works.

I get error when running karma:

```
FAILED TESTS:
  The test widget
    x  should work
      Chrome 51.0.2704 (Windows 7 0.0.0)
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    TypeError: component.dispose is not a function
        at Object.<anonymous> (webpack:///test/unit/test.spec.ts:19:4 <- spec-bundle.js:20965:19)
```

**Comment by EisenbergEffect** [comment]
Sounds like a possible configuration problem with your test setup. Perhaps @niieani can provide some feedback.

**Comment by niieani** [comment]
I haven't actually tested aurelia-testing with webpack yet, so it's possible there's some bug involved. I'll have to do that soon and let you know.

**Comment by suneelv** [comment]
```
WARN: '%cUnhandled rejection TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (http://localhost:19877/base/spec-bundle.js?b62f4b431ec7e710e950586d0cb2cd622f9ea33b:53:29)
    at http://localhost:19877/base/spec-bundle.js?b62f4b431ec7e710e950586d0cb2cd622f9ea33b:43259:50
From previous event:
    at http://localhost:19877/base/spec-bundle.js?b62f4b431ec7e710e950586d0cb2cd622f9ea33b:43258:83
From previous event:
    at WebpackLoader._import (http://localhost:19877/base/spec-bundle.js?b62f4b431ec7e710e950586d0cb2cd622f9ea33b:43253:12)
    at http://localhost:19877/base/spec-bundle.js?b62f4b431ec7e710e950586d0cb2cd622f9ea33b:43309:16
From previous event:
    at WebpackLoader.loadModule (http://localhost:19877/base/spec-bundle.js?b62f4b431ec7e710e950586d0cb2cd622f9ea33b:43307:12)
    at http://localhost:19877/base/spec-bundle.js?b62f4b431ec7e710e950586d0cb2cd622f9ea33b:43077:12
From previous event:
    at run (http://localhost:19877/base/spec-bundle.js?b62f4b431ec7e710e950586d0cb2cd622f9ea33b:43072:24)
    at Object.<anonymous> (http://localhost:19877/base/spec-bundle.js?b62f4b431ec7e710e950586d0cb2cd622f9ea33b:43099:1)
    at Object.<anonymous> (http://localhost:19877/base/spec-bundle.js?b62f4b431ec7e710e950586d0cb2cd622f9ea33b:43100:30)
    at __webpack_require__ (http://localhost:19877/base/spec-bundle.js?b62f4b431ec7e710e950586d0cb2cd622f9ea33b:53:30)
    at Object.<anonymous> (http://localhost:19877/base/spec-bundle.js?b62f4b431ec7e710e950586d0cb2cd622f9ea33b:71416:35)
    at __webpack_require__ (http://localhost:19877/base/spec-bundle.js?b62f4b431ec7e710e950586d0cb2cd622f9ea33b:53:30)
    at webpackContext (http://localhost:19877/base/spec-bundle.js?b62f4b431ec7e710e950586d0cb2cd622f9ea33b:70904:9)
    at Array.map (native)
    at requireAll (http://localhost:19877/base/spec-bundle.js?b62f4b431ec7e710e950586d0cb2cd622f9ea33b:72388:32)
    at Object.<anonymous> (http://localhost:19877/base/spec-bundle.js?b62f4b431ec7e710e950586d0cb2cd622f9ea33b:72392:15)
    at __webpack_require__ (http://localhost:19877/base/spec-bundle.js?b62f4b431ec7e710e950586d0cb2cd622f9ea33b:53:30)
    at http://localhost:19877/base/spec-bundle.js?b62f4b431ec7e710e950586d0cb2cd622f9ea33b:129:18
    at http://localhost:19877/base/spec-bundle.js?b62f4b431ec7e710e950586d0cb2cd622f9ea33b:132:10', 'color: red'
WARN: '%cUnhandled rejection TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (http://localhost:19877/base/spec-bundle.js?b62f4b431ec7e710e950586d0cb2cd622f9ea33b:53:29)
    at http://localhost:19877/base/spec-bundle.js?b62f4b431ec7e710e950586d0cb2cd622f9ea33b:43259:50
From previous event:
    at http://localhost:19877/base/spec-bundle.js?b62f4b431ec7e710e950586d0cb2cd622f9ea33b:43258:83
From previous event:
    at WebpackLoader._import (http://localhost:19877/base/spec-bundle.js?b62f4b431ec7e710e950586d0cb2cd622f9ea33b:43253:12)
    at http://localhost:19877/base/spec-bundle.js?b62f4b431ec7e710e950586d0cb2cd622f9ea33b:43309:16
From previous event:
    at WebpackLoader.loadModule (http://localhost:19877/base/spec-bundle.js?b62f4b431ec7e710e950586d0cb2cd622f9ea33b:43307:12)
    at http://localhost:19877/base/spec-bundle.js?b62f4b431ec7e710e950586d0cb2cd622f9ea33b:43077:12
From previous event:
    at run (http://localhost:19877/base/spec-bundle.js?b62f4b431ec7e710e950586d0cb2cd622f9ea33b:43072:24)
    at Object.<anonymous> (http://localhost:19877/base/spec-bundle.js?b62f4b431ec7e710e950586d0cb2cd622f9ea33b:43099:1)
    at Object.<anonymous> (http://localhost:19877/base/spec-bundle.js?b62f4b431ec7e710e950586d0cb2cd622f9ea33b:43100:30)
    at __webpack_require__ (http://localhost:19877/base/spec-bundle.js?b62f4b431ec7e710e950586d0cb2cd622f9ea33b:53:30)
    at Object.<anonymous> (http://localhost:19877/base/spec-bundle.js?b62f4b431ec7e710e950586d0cb2cd622f9ea33b:71416:35)
    at __webpack_require__ (http://localhost:19877/base/spec-bundle.js?b62f4b431ec7e710e950586d0cb2cd622f9ea33b:53:30)
    at webpackContext (http://localhost:19877/base/spec-bundle.js?b62f4b431ec7e710e950586d0cb2cd622f9ea33b:70904:9)
    at Array.map (native)
    at requireAll (http://localhost:19877/base/spec-bundle.js?b62f4b431ec7e710e950586d0cb2cd622f9ea33b:72388:32)
    at Object.<anonymous> (http://localhost:19877/base/spec-bundle.js?b62f4b431ec7e710e950586d0cb2cd622f9ea33b:72392:15)
    at __webpack_require__ (http://localhost:19877/base/spec-bundle.js?b62f4b431ec7e710e950586d0cb2cd622f9ea33b:53:30)
    at http://localhost:19877/base/spec-bundle.js?b62f4b431ec7e710e950586d0cb2cd622f9ea33b:129:18
    at http://localhost:19877/base/spec-bundle.js?b62f4b431ec7e710e950586d0cb2cd622f9ea33b:132:10', 'color: red'
```

I am getting the following when trying to test a custom element using es6 webpack

![screen shot 2016-07-24 at 10 25 32 pm](https://cloud.githubusercontent.com/assets/6492948/17086284/0bea7a76-51ee-11e6-9924-eae95a351f9a.png)

Also the documentation doesn't mention that we should import bootstrap from 'aurelia-bootstrapper-webpack' when using webpack.

**Comment by doodlesbykumbi** [comment]
@EisenbergEffect @niieani I'm experiencing the same issue. Is anyone currently working on this ?

**Comment by doodlesbykumbi** [comment]
After some digging, I can see that the uncaught error is from when the webpack-loader tries to call `require.ensure` in `WebpackLoader.prototype._import`. Some other strange stuff is happening there e.g. trying to access the variable `require` results in an error being thrown. `Error{code: 'MODULE_NOT_FOUND`

**Comment by niieani** [comment]
@doodlesbykumbi do you have the latest versions? see if `npm update` would help

**Comment by doodlesbykumbi** [comment]
@niieani I've got the latest everything.

Here is my test

```
import './setup';
import {StageComponent} from 'aurelia-testing';
import {bootstrap} from 'aurelia-bootstrapper-webpack';

describe('MyAttribute', () => {
  let component;

  beforeEach(() => {
    component = StageComponent
        .withResources()
        .inView('<div style="background-color: red">Bob</div>')
        .boundTo({ color: 'blue' });
  });

  it('should set the background color to provided color', done => {
     component.create(bootstrap).then(() => {
        expect(component.element.style.backgroundColor).toBe('blue');
        done();
     }).catch((e) => {
         console.log('THERE IS AN ERROR IN HERE SOMEWERE', e)
     })
  });

  afterEach(() => {
    component.dispose();
  });
});
```

**Comment by niieani** [comment]
OK, seems to break at `modules[moduleId].call` when a module doesn't exist in the cache. I'll try to get a fix out soon.

**Comment by niieani** [comment]
Feel free to track the related issue https://github.com/aurelia/loader-webpack/issues/19.

**Comment by doodlesbykumbi** [comment]
To whom it may concern :dancer: 

I found a quick fix after chasing the trail a bit.
In `test/unit/setup.ts`, which should be imported into any of the tests that interact with Aurelia, add the following and you should be good to go for now.

```
import 'aurelia-templating-binding';
import 'aurelia-templating-resources';
import 'aurelia-event-aggregator';
import 'aurelia-history-browser';
import 'aurelia-templating-router';
```

**Comment by niieani** [comment]
Actually there are two separate related issues here
one of them is that some resources are missing when running the tests, so when using your workaround by manually importing them, the missing resources are added
The other problem is that when a module is missing and modules[moduleId].call is called while modules[moduleId] is undefined, causes the error you saw. The proper fix will be to add the resources for such tests, by adding the `AureliaWebpackPlugin` into the config when the environment is test.
The best way to fix this would be to change the Webpack skeletons so that they handle the `aurelia-testing` module differently to other, non-aurelia-testing karma tests, or somehow make an universal solution.

Thanks for the workaround. It's great, though it won't work if you use custom Aurelia resources (or you'd need to import them too!).

**Comment by mttmccb** [comment]
The work around does work for me (using esnext webpack), starts with...

`WARN: '%cUnhandled rejection TypeError: Cannot read property 'call' of undefined`

**Comment by spencewood** [comment]
I have been effectively held back in updating to the 1.0.0 Aurelia release by this issue. We use Aurelia for a large app, and have thousands of tests using the old `templatingEngine.createViewModelForUnitTest()`. Updating to aurelia-testing using the webpack loader has given me the same results as OP. Simply adding a few additional resources for every test suite has not solved this issue in our case.

Any movement on this issue would be fantastic. I'd love to get out of beta.

**Comment by EisenbergEffect** [comment]
@niieani Can you look into this please?

**Comment by niieani** [comment]
@EisenbergEffect already have; the test config bundle config needs to include the WebpackPlugin. I'll try to get a fix into to skeleton-navigation and people can copy the same change from there.

**Comment by obiyoda** [comment]
@niieani can you post the fix here so those of us that are waiting for this to make it out can make the fix? I don't understand what you mean by the "the test config bundle needs to include the webpackPlugin". Or if you have a branch or something you can point us to that shows what needs to be done that would be awesome. Thanks for your great work on the webpack plugin!

**Comment by niieani** [comment]
@obiyoda I know the problem, but not how to implement the solution yet. Might be configuration files [here](https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-typescript-webpack/test).

**Comment by EisenbergEffect** [comment]
Closing this question to track the issue here: https://github.com/aurelia/loader-webpack/issues/19

**Comment by niieani** [comment]
Fixed by https://github.com/aurelia/skeleton-navigation/pull/714

**Comment by nashwaan** [comment]
Sorry @niieani, but the new skeleton still doesn't solve this problem yet (**when running the tests in the browser via karma**). I still get exactly the same error as posted by the OP:

`
 Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        Error: Cannot call ComponentTester.dispose() before ComponentTester.create()
`

**Comment by niieani** [comment]
Thanks for reporting. It might be a problem with the testing framework. We'll try to investigate.

**Comment by waywardz** [comment]
Has anyone had a chance to look at this?  Any suggestions for workarounds?

**Comment by niieani** [comment]
As a workaround I'd suggest using a node-based unit-testing framework (jest is available in the latest webpack skeletons). We're also open to PRs with fixes, as I don't currently have the time to investigate this issue.

**Comment by niieani** [comment]
An example of using Karma/Mocha with `aurelia-testing` landed in master, in the skeleton-navigation repo.

**Comment by nashwaan** [comment]
The updated skeleton repo has solved this issue. Thanks @niieani .
